### ISSUE TITLE
Repo is missing an open source license

### ISSUE THREAD

**Issue by kungfuchicken** [oss-slu/Enhancing-Bioinformatics-Research-through-LLM#24]
This project needs an OSI approved open source software license included in it. This is required regardless of whether we are expecting any outside contributions currently or in the near future.

**Comment by AjithAkuthota23** [comment]
https://github.com/oss-slu/Enhancing-Bioinformatics-Research-through-LLM/commit/66d2f3d5bd58347703907b771acc4eece636354f


Added license file to the project
