### ISSUE TITLE
Create the API documentation page and Reference page with random information and test it

### ISSUE THREAD

**Issue by AjithAkuthota23** [oss-slu/Enhancing-Bioinformatics-Research-through-LLM#7]
Create a API documentation and reference page with sample data, since the model is not integrated with the UI yet and since it doesn't recommend any suggestions right now.

### API Documentation Checklist

- [ ] **API Name**  
  - Description: Provide details about the API here.

- [ ] **Usage**  
  - Explain how to use the API.

- [ ] **Endpoint**  

- [ ] **Method**  
  - Specify if the method is `GET` or `POST` (or another method).

- [ ] **Parameters**  
  - List the parameters required for the API (e.g., query params, body params).
  - Example format:  
    - `param1`: Description of param1  
    - `param2`: Description of param2

- [ ] **Example**  
  - Provide an example usage of the API.
  

![image](https://github.com/user-attachments/assets/559754b1-e1f6-4f62-98af-9da5b87be816)

### References Checklist

- [ ] **Author Name**
  
- [ ] **Year**

- [ ] **Title**

- [ ] **Journal**

- [ ] **Volume**

- [ ] **Pages**

![image](https://github.com/user-attachments/assets/ba5ef17e-e5bf-4a4c-8241-9c815aa4e6bc)

**Comment by fduffoo** [comment]
Hello, I would love to work on this. Please assign it to me.
